In [1]:
import duckdb

CSV = "../data/2025_LoL_esports_match_data_from_OraclesElixir.csv"

duckdb.sql(
    f" SELECT COUNT (*) FROM '{CSV}'"
)

┌──────────────┐
│ count_star() │
│    int64     │
├──────────────┤
│       120492 │
└──────────────┘

In [4]:
# import pandas as pd
# pd.set_option('display.max_rows', None)
duckdb.sql(
    f"DESCRIBE SELECT * FROM '{CSV}'"
).df()

                  column_name column_type null   key default extra
0                      gameid     VARCHAR  YES  None    None  None
1            datacompleteness     VARCHAR  YES  None    None  None
2                         url     VARCHAR  YES  None    None  None
3                      league     VARCHAR  YES  None    None  None
4                        year      BIGINT  YES  None    None  None
5                       split     VARCHAR  YES  None    None  None
6                    playoffs      BIGINT  YES  None    None  None
7                        date   TIMESTAMP  YES  None    None  None
8                        game      BIGINT  YES  None    None  None
9                       patch      DOUBLE  YES  None    None  None
10              participantid      BIGINT  YES  None    None  None
11                       side     VARCHAR  YES  None    None  None
12                   position     VARCHAR  YES  None    None  None
13                 playername     VARCHAR  YES  None    None  None
14                   playerid     VARCHAR  YES  None    None  None
15                   teamname     VARCHAR  YES  None    None  None
16                     teamid     VARCHAR  YES  None    None  None
17                  firstPick      BIGINT  YES  None    None  None
18                   champion     VARCHAR  YES  None    None  None
19                       ban1     VARCHAR  YES  None    None  None
20                       ban2     VARCHAR  YES  None    None  None
21                       ban3     VARCHAR  YES  None    None  None
22                       ban4     VARCHAR  YES  None    None  None
23                       ban5     VARCHAR  YES  None    None  None
24                      pick1     VARCHAR  YES  None    None  None
25                      pick2     VARCHAR  YES  None    None  None
26                      pick3     VARCHAR  YES  None    None  None
27                      pick4     VARCHAR  YES  None    None  None
28                      pick5     VARCHAR  YES  None    None  None
29                 gamelength      BIGINT  YES  None    None  None
30                     result      BIGINT  YES  None    None  None
31                      kills      BIGINT  YES  None    None  None
32                     deaths      BIGINT  YES  None    None  None
33                    assists      BIGINT  YES  None    None  None
34                  teamkills      BIGINT  YES  None    None  None
35                 teamdeaths      BIGINT  YES  None    None  None
36                doublekills      BIGINT  YES  None    None  None
37                triplekills      BIGINT  YES  None    None  None
38                quadrakills      BIGINT  YES  None    None  None
39                 pentakills      BIGINT  YES  None    None  None
40                 firstblood      BIGINT  YES  None    None  None
41             firstbloodkill      BIGINT  YES  None    None  None
42           firstbloodassist      BIGINT  YES  None    None  None
43           firstbloodvictim      BIGINT  YES  None    None  None
44                   team kpm      DOUBLE  YES  None    None  None
45                       ckpm      DOUBLE  YES  None    None  None
46                firstdragon      BIGINT  YES  None    None  None
47                    dragons      BIGINT  YES  None    None  None
48                opp_dragons      BIGINT  YES  None    None  None
49            elementaldrakes      BIGINT  YES  None    None  None
50        opp_elementaldrakes      BIGINT  YES  None    None  None
51                  infernals      BIGINT  YES  None    None  None
52                  mountains      BIGINT  YES  None    None  None
53                     clouds      BIGINT  YES  None    None  None
54                     oceans      BIGINT  YES  None    None  None
55                  chemtechs      BIGINT  YES  None    None  None
56                   hextechs      BIGINT  YES  None    None  None
57     dragons (type unknown)      BIGINT  YES  None    None  None
58                     elders      BIGINT  YES  None    None  None
59                 opp_elders      BIGINT  YES  None    None  None
60                firstherald      BIGINT  YES  None    None  None
61                    heralds      BIGINT  YES  None    None  None
62                opp_heralds      BIGINT  YES  None    None  None
63                 void_grubs      BIGINT  YES  None    None  None
64             opp_void_grubs      BIGINT  YES  None    None  None
65                 firstbaron      BIGINT  YES  None    None  None
66                     barons      BIGINT  YES  None    None  None
67                 opp_barons      BIGINT  YES  None    None  None
68                   atakhans      BIGINT  YES  None    None  None
69               opp_atakhans      BIGINT  YES  None    None  None
70                 firsttower      BIGINT  YES  None    None  None
71                     towers      BIGINT  YES  None    None  None
72                 opp_towers      BIGINT  YES  None    None  None
73              firstmidtower      BIGINT  YES  None    None  None
74         firsttothreetowers      BIGINT  YES  None    None  None
75               turretplates      BIGINT  YES  None    None  None
76           opp_turretplates      BIGINT  YES  None    None  None
77                 inhibitors      BIGINT  YES  None    None  None
78             opp_inhibitors      BIGINT  YES  None    None  None
79          damagetochampions      BIGINT  YES  None    None  None
80                        dpm      DOUBLE  YES  None    None  None
81                damageshare      DOUBLE  YES  None    None  None
82       damagetakenperminute      DOUBLE  YES  None    None  None
83   damagemitigatedperminute      DOUBLE  YES  None    None  None
84             damagetotowers      BIGINT  YES  None    None  None
85                wardsplaced      BIGINT  YES  None    None  None
86                        wpm      DOUBLE  YES  None    None  None
87                wardskilled      BIGINT  YES  None    None  None
88                       wcpm      DOUBLE  YES  None    None  None
89         controlwardsbought      BIGINT  YES  None    None  None
90                visionscore      BIGINT  YES  None    None  None
91                       vspm      DOUBLE  YES  None    None  None
92                  totalgold      BIGINT  YES  None    None  None
93                 earnedgold      BIGINT  YES  None    None  None
94                 earned gpm      DOUBLE  YES  None    None  None
95            earnedgoldshare      DOUBLE  YES  None    None  None
96                  goldspent      BIGINT  YES  None    None  None
97                       gspd      DOUBLE  YES  None    None  None
98                        gpr      DOUBLE  YES  None    None  None
99                   total cs      BIGINT  YES  None    None  None
100               minionkills      BIGINT  YES  None    None  None
101              monsterkills      BIGINT  YES  None    None  None
102     monsterkillsownjungle      BIGINT  YES  None    None  None
103   monsterkillsenemyjungle      BIGINT  YES  None    None  None
104                      cspm      DOUBLE  YES  None    None  None
105                  goldat10      BIGINT  YES  None    None  None
106                    xpat10      BIGINT  YES  None    None  None
107                    csat10      BIGINT  YES  None    None  None
108              opp_goldat10      BIGINT  YES  None    None  None
109                opp_xpat10      BIGINT  YES  None    None  None
110                opp_csat10      BIGINT  YES  None    None  None
111              golddiffat10      BIGINT  YES  None    None  None
112                xpdiffat10      BIGINT  YES  None    None  None
113                csdiffat10      BIGINT  YES  None    None  None
114                 killsat10      BIGINT  YES  None    None  None
115               assistsat10      BIGINT  YES  None    None  None
116                deathsat10      BIGINT  YES  None    None  None
117             opp_killsat10      BIGINT  YES  None    None  None
118           opp_assistsat10      BIGINT  YES  None    None  None
119            opp_deathsat10      BIGINT  YES  None    None  None
120                  goldat15      BIGINT  YES  None    None  None
121                    xpat15      BIGINT  YES  None    None  None
122                    csat15      BIGINT  YES  None    None  None
123              opp_goldat15      BIGINT  YES  None    None  None
124                opp_xpat15      BIGINT  YES  None    None  None
125                opp_csat15      BIGINT  YES  None    None  None
126              golddiffat15      BIGINT  YES  None    None  None
127                xpdiffat15      BIGINT  YES  None    None  None
128                csdiffat15      BIGINT  YES  None    None  None
129                 killsat15      BIGINT  YES  None    None  None
130               assistsat15      BIGINT  YES  None    None  None
131                deathsat15      BIGINT  YES  None    None  None
132             opp_killsat15      BIGINT  YES  None    None  None
133           opp_assistsat15      BIGINT  YES  None    None  None
134            opp_deathsat15      BIGINT  YES  None    None  None
135                  goldat20      BIGINT  YES  None    None  None
136                    xpat20      BIGINT  YES  None    None  None
137                    csat20      BIGINT  YES  None    None  None
138              opp_goldat20      BIGINT  YES  None    None  None
139                opp_xpat20      BIGINT  YES  None    None  None
140                opp_csat20      BIGINT  YES  None    None  None
141              golddiffat20      BIGINT  YES  None    None  None
142                xpdiffat20      BIGINT  YES  None    None  None
143                csdiffat20      BIGINT  YES  None    None  None
144                 killsat20      BIGINT  YES  None    None  None
145               assistsat20      BIGINT  YES  None    None  None
146                deathsat20      BIGINT  YES  None    None  None
147             opp_killsat20      BIGINT  YES  None    None  None
148           opp_assistsat20      BIGINT  YES  None    None  None
149            opp_deathsat20      BIGINT  YES  None    None  None
150                  goldat25      BIGINT  YES  None    None  None
151                    xpat25      BIGINT  YES  None    None  None
152                    csat25      BIGINT  YES  None    None  None
153              opp_goldat25      BIGINT  YES  None    None  None
154                opp_xpat25      BIGINT  YES  None    None  None
155                opp_csat25      BIGINT  YES  None    None  None
156              golddiffat25      BIGINT  YES  None    None  None
157                xpdiffat25      BIGINT  YES  None    None  None
158                csdiffat25      BIGINT  YES  None    None  None
159                 killsat25      BIGINT  YES  None    None  None
160               assistsat25      BIGINT  YES  None    None  None
161                deathsat25      BIGINT  YES  None    None  None
162             opp_killsat25      BIGINT  YES  None    None  None
163           opp_assistsat25      BIGINT  YES  None    None  None
164            opp_deathsat25      BIGINT  YES  None    None  None

In [9]:
duckdb.sql(f"""
    SELECT gameid, side, position, playername, champion, ban1, ban2, ban3, ban4, ban5, pick1, pick2, pick3, pick4, pick5, result
    FROM '{CSV}'
    LIMIT 24
""").df()

,gameid,side,position,playername,champion,ban1,ban2,ban3,ban4,ban5,pick1,pick2,pick3,pick4,pick5,result
0,LOLTMNT03_179647,Blue,top,PatkicaA,Gnar,Vi,Skarner,Corki,K'Sante,Sylas,NaN,NaN,NaN,NaN,NaN,0
1,LOLTMNT03_179647,Blue,jng,Joinze,Maokai,Vi,Skarner,Corki,K'Sante,Sylas,NaN,NaN,NaN,NaN,NaN,0
2,LOLTMNT03_179647,Blue,mid,Sayn,Hwei,Vi,Skarner,Corki,K'Sante,Sylas,NaN,NaN,NaN,NaN,NaN,0
3,LOLTMNT03_179647,Blue,bot,Shiganari,Jinx,Vi,Skarner,Corki,K'Sante,Sylas,NaN,NaN,NaN,NaN,NaN,0
4,LOLTMNT03_179647,Blue,sup,Lekcyc,Leona,Vi,Skarner,Corki,K'Sante,Sylas,NaN,NaN,NaN,NaN,NaN,0
5,LOLTMNT03_179647,Red,top,Nille,Renekton,Yone,Viktor,Aurora,Nocturne,Jarvan IV,NaN,NaN,NaN,NaN,NaN,1
6,LOLTMNT03_179647,Red,jng,SPOOKY,Ivern,Yone,Viktor,Aurora,Nocturne,Jarvan IV,NaN,NaN,NaN,NaN,NaN,1
7,LOLTMNT03_179647,Red,mid,Nafkelah,Orianna,Yone,Viktor,Aurora,Nocturne,Jarvan IV,NaN,NaN,NaN,NaN,NaN,1
8,LOLTMNT03_179647,Red,bot,Soldier,Varus,Yone,Viktor,Aurora,Nocturne,Jarvan IV,NaN,NaN,NaN,NaN,NaN,1
9,LOLTMNT03_179647,Red,sup,Steeelback,Braum,Yone,Viktor,Aurora,Nocturne,Jarvan IV,NaN,NaN,NaN,NaN,NaN,1
10,LOLTMNT03_179647,Blue,team,NaN,NaN,Vi,Skarner,Corki,K'Sante,Sylas,Maokai,Jinx,Leona,Hwei,Gnar,0
11,LOLTMNT03_179647,Red,team,NaN,NaN,Yone,Viktor,Aurora,Nocturne,Jarvan IV,Varus,Ivern,Braum,Renekton,Orianna,1
12,LOLTMNT06_96134,Blue,top,Potent,K'Sante,Kalista,Aurora,Skarner,Akali,Ziggs,NaN,NaN,NaN,NaN,NaN,1
13,LOLTMNT06_96134,Blue,jng,CRoNiiK,Ivern,Kalista,Aurora,Skarner,Akali,Ziggs,NaN,NaN,NaN,NaN,NaN,1
14,LOLTMNT06_96134,Blue,mid,xKenzuke,Azir,Kalista,Aurora,Skarner,Akali,Ziggs,NaN,NaN,NaN,NaN,NaN,1
15,LOLTMNT06_96134,Blue,bot,HARPOON,Varus,Kalista,Aurora,Skarner,Akali,Ziggs,NaN,NaN,NaN,NaN,NaN,1
16,LOLTMNT06_96134,Blue,sup,Leon,Rell,Kalista,Aurora,Skarner,Akali,Ziggs,NaN,NaN,NaN,NaN,NaN,1
17,LOLTMNT06_96134,Red,top,MAT,Renekton,Fiora,Nocturne,Ashe,Leona,Yone,NaN,NaN,NaN,NaN,NaN,0
18,LOLTMNT06_96134,Red,jng,Roshan,Sejuani,Fiora,Nocturne,Ashe,Leona,Yone,NaN,NaN,NaN,NaN,NaN,0
19,LOLTMNT06_96134,Red,mid,Artoria,Orianna,Fiora,Nocturne,Ashe,Leona,Yone,NaN,NaN,NaN,NaN,NaN,0
20,LOLTMNT06_96134,Red,bot,Xicor,Corki,Fiora,Nocturne,Ashe,Leona,Yone,NaN,NaN,NaN,NaN,NaN,0
21,LOLTMNT06_96134,Red,sup,Highway,Nautilus,Fiora,Nocturne,Ashe,Leona,Yone,NaN,NaN,NaN,NaN,NaN,0
22,LOLTMNT06_96134,Blue,team,NaN,NaN,Kalista,Aurora,Skarner,Akali,Ziggs,Varus,K'Sante,Ivern,Azir,Rell,1
23,LOLTMNT06_96134,Red,team,NaN,NaN,Fiora,Nocturne,Ashe,Leona,Yone,Corki,Sejuani,Renekton,Orianna,Nautilus,0

In [7]:
duckdb.sql(f"""
    SELECT patch, COUNT(DISTINCT gameid) AS n_games
    FROM '{CSV}'
    GROUP BY patch
    ORDER BY patch
""").df()

┌────────┬─────────┐
│ patch  │ n_games │
│ double │  int64  │
├────────┼─────────┤
│  15.01 │     315 │
│  15.02 │     536 │
│  15.03 │     569 │
│  15.04 │     371 │
│  15.05 │     214 │
│  15.06 │     464 │
│  15.07 │     820 │
│  15.08 │     796 │
│  15.09 │     875 │
│   15.1 │     652 │
│     ·  │      ·  │
│     ·  │      ·  │
│     ·  │      ·  │
│  15.15 │     637 │
│  15.16 │     613 │
│  15.17 │     622 │
│  15.18 │     180 │
│  15.19 │     378 │
│   15.2 │     192 │
│  15.21 │      60 │
│  15.22 │      19 │
│  15.23 │      56 │
│  15.24 │      78 │
└────────┴─────────┘
      24 rows
     (20 shown)

In [8]:
duckdb.sql(f"""
    SELECT COUNT(*) FROM (
        SELECT DISTINCT champion, patch
        FROM '{CSV}'
        WHERE position != 'team'
    )
""").df()

   count_star()
0          3183

In [13]:
# Check if the ban's and pick's order are correct with gol.gg
df_search = duckdb.sql(f"""
    SELECT gameid, league, date, teamname, side, patch
    FROM '{CSV}'
    WHERE teamname IN ('T1', 'G2 Esports', 'Gen.G')
        AND position = 'team'
        AND league IN ('LCK', 'LEC', 'WLDs', 'MSI')
    LIMIT 2
""").df()

print(df_search)

# Replace 'YOUR_GAME_ID' with the ID you found
df_match = duckdb.sql(f"""
    SELECT side, position, teamname, champion, 
           ban1, ban2, ban3, ban4, ban5, 
           pick1, pick2, pick3, pick4, pick5
    FROM '{CSV}'
    WHERE gameid = 'LOLTMNT03_185025'
      AND position = 'team' -- Filters down to just the two team rows showing the full draft
""").df()

print(df_match)

             gameid league                date teamname  side  patch
0  LOLTMNT03_185025    LCK 2025-01-16 11:11:06       T1   Red  15.01
1  LOLTMNT03_185042    LCK 2025-01-16 11:55:28       T1  Blue  15.01
   side position   teamname champion     ban1     ban2     ban3     ban4  \
0  Blue     team  Dplus Kia     None  Kalista  Sejuani    Varus    Braum
1   Red     team         T1     None       Vi  Skarner  K'Sante  LeBlanc

    ban5    pick1   pick2  pick3    pick4   pick5
0  Poppy  Nidalee  Ezreal  Leona  Ambessa   Jayce
1    Jax     Ashe    Zyra   Yone     Rell  Gragas